package main

import (
	"cmp"
	"fmt"
	"go/ast"
	"go/doc"
	"go/parser"
	"go/token"
	"log"
	"nix/derivation"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"text/template"
)

type TestAttrs struct {
	ImportPath string
	Srcs       []string
	XSrcs      []string
	Data       string
}

type importPackage struct {
	Name string
	Path string
}

type testCase struct {
	Package string
	Name    string
}

type example struct {
	testCase
	Output    string
	Unordered bool
}

type testPackage struct {
	ImportPath   string
	SupportsFuzz bool
	Imports      []importPackage

	Tests       []testCase
	Benchmarks  []testCase
	FuzzTargets []testCase
	Examples    []example

	TestMain string

	Data string
}

var testMainTmpl = `// Generated by gopkg2nix-incremental.
//
// Do not edit by hand.

package main

import (
	"fmt"
	"os"
{{- if .TestMain}}
	"reflect"
{{- end}}
	"testing"
	"testing/internal/testdeps"
{{- range .Imports}}

	{{.Name}} "{{.Path}}"
{{- end}}
)

var tests = []testing.InternalTest{
{{- range .Tests}}
	{"{{.Name}}", {{.Package}}.{{.Name}} },
{{- end}}
}

var benchmarks = []testing.InternalBenchmark{
{{- range .Benchmarks}}
	{"{{.Name}}", {{.Package}}.{{.Name}} },
{{- end}}
}

{{if .SupportsFuzz -}}
var fuzzTargets = []testing.InternalFuzzTarget{
{{- range .FuzzTargets}}
	{"{{.Name}}", {{.Package}}.{{.Name}} },
{{- end}}
}
{{- end}}

var examples = []testing.InternalExample{
{{- range .Examples}}
	{
		Name: "{{.Name}}",
		F: {{.Package}}.{{.Name}},
		Output: {{printf "%q" .Output}},
		Unordered: {{.Unordered}},
	},
{{- end}}
}

var out *os.File

func init() {
	testdeps.ImportPath = {{printf "%q" .ImportPath}}

	var outPath string
	for i, arg := range os.Args {
		if arg == "-nix.output" && i+1 < len(os.Args) {
			outPath = os.Getenv(os.Args[i+1])
			os.Args = append(os.Args[:i], os.Args[i+2:]...)
			clear(os.Args[len(os.Args) : len(os.Args)+2])

			break
		}
	}
	if outPath == "" {
		return
	}

	var err error
	if out, err = os.Create(outPath); err != nil {
		panic(fmt.Sprintf("failed to create result file: %v", err))
	}
}

func main() {
{{- if .Data}}
	if err := os.Chdir("{{.Data}}"); err != nil {
		panic(fmt.Sprintf("failed to change to the data directory: %v", err))
	}
{{end}}

{{- if .SupportsFuzz}}
	m := testing.MainStart(
		testdeps.TestDeps{},
		tests,
		benchmarks,
		fuzzTargets,
		examples,
	)
{{else}}
	m := testing.MainStart(testdeps.TestDeps{}, tests, benchmarks, examples)
{{end}}

{{- if .TestMain}}
	{{.TestMain}}.TestMain(m)

	// TestMain may or may not call os.Exit. If it doesn't, forward status as
	// if we ran it ourselves. See https://github.com/golang/go/issues/34129
	res := int(reflect.ValueOf(m).Elem().FieldByName("exitCode").Int())
{{- else}}
	res := m.Run()
{{- end}}

	if out != nil && res == 0 {
		fmt.Fprintln(out, "PASS")
		out.Close()
	}
	os.Exit(res)
}
`

// verifyTestSignature returns an error if the test function has the wrong
// function signature.
func verifyTestSignature(
	fset *token.FileSet,
	fn *ast.FuncDecl,
	arg string,
) error {
	if fn.Type.TypeParams.NumFields() == 0 &&
		fn.Type.Params.NumFields() == 1 &&
		fn.Type.Results.NumFields() == 0 {
		starExpr, ok := fn.Type.Params.List[0].Type.(*ast.StarExpr)
		if ok {
			selExpr, ok := starExpr.X.(*ast.SelectorExpr)
			if ok && selExpr.Sel.Name == arg {
				return nil
			}
		}
	}

	pos := fset.Position(fn.Pos())
	return fmt.Errorf(
		"%s: wrong signature, expected: func %s(%s *testing.%s)",
		pos,
		fn.Name.Name,
		strings.ToLower(arg),
		arg,
	)
}

// loadTest searches through a file and loads every test function declared
// inside.
func (t *testPackage) loadTest(
	fset *token.FileSet,
	pkg string,
	path string,
) (string, bool, error) {
	file, err := os.Open(path)
	if err != nil {
		return "", false, err
	}
	defer file.Close()

	parsed, err := parser.ParseFile(fset, path, file, parser.ParseComments)
	if err != nil {
		return "", false, err
	}
	enable := false

	for _, d := range parsed.Decls {
		fn, ok := d.(*ast.FuncDecl)
		if !ok || fn.Recv != nil {
			continue
		}

		if fn.Name.Name == "TestMain" {
			if err := verifyTestSignature(fset, fn, "M"); err != nil {
				return "", false, err
			}
			t.TestMain = pkg
			enable = true
		} else {
			tc := testCase{Package: pkg, Name: fn.Name.Name}
			switch {
			case strings.HasPrefix(fn.Name.Name, "Test"):
				if err := verifyTestSignature(fset, fn, "T"); err != nil {
					return "", false, err
				}
				t.Tests = append(t.Tests, tc)
				enable = true
			case strings.HasPrefix(fn.Name.Name, "Benchmark"):
				if err := verifyTestSignature(fset, fn, "B"); err != nil {
					return "", false, err
				}
				t.Benchmarks = append(t.Benchmarks, tc)
				enable = true
			case strings.HasPrefix(fn.Name.Name, "Fuzz"):
				if err := verifyTestSignature(fset, fn, "F"); err != nil {
					return "", false, err
				}
				t.FuzzTargets = append(t.FuzzTargets, tc)
				enable = true
			}
		}
	}

	// sort examples by the order they appear in the file. See
	// https://github.com/golang/go/issues/4662
	ex := doc.Examples(parsed)
	slices.SortFunc(ex, func(a, b *doc.Example) int {
		return cmp.Compare(a.Order, b.Order)
	})
	for _, e := range doc.Examples(parsed) {
		if e.Output == "" && !e.EmptyOutput {
			continue
		}
		t.Examples = append(t.Examples, example{
			testCase:  testCase{Package: pkg, Name: "Example" + e.Name},
			Output:    e.Output,
			Unordered: e.Unordered,
		})
		enable = true
	}

	return parsed.Name.Name, enable, nil
}

// findTestCases searches through a list of files and generates a list of test
// cases to include in the generated package.
func (t *testPackage) findTestCases(
	name string,
	importPath string,
	srcs []string,
) (string, error) {
	importPkg := importPackage{Name: name, Path: importPath}

	fset := token.NewFileSet()
	pkgsSrcs := make(map[string][]string)
	for _, path := range srcs {
		parsedName, enable, err := t.loadTest(fset, name, path)
		if err != nil {
			return "", err
		}

		pkgsSrcs[parsedName] = append(pkgsSrcs[parsedName], path)
		if enable {
			i, found := slices.BinarySearchFunc(
				t.Imports,
				importPkg,
				func(a, b importPackage) int {
					return strings.Compare(a.Name, b.Name)
				},
			)
			if !found {
				t.Imports = slices.Insert(t.Imports, i, importPkg)
			}
		}
	}

	if len(pkgsSrcs) > 1 {
		var err ConflictingPackageError
		for pkgName, srcs := range pkgsSrcs {
			err.pkgs = append(err.pkgs, pkgName)
			err.srcs = append(err.srcs, srcs)
		}
		return "", &err
	}

	for realName := range pkgsSrcs {
		return realName, nil
	}
	return "", nil
}

// setupData creates an output directory containing a symbolic link to the test
// data if there is any.
func setupData(dataDir string, pkg *testPackage) error {
	if dataDir == "" {
		return nil
	}

	var err error
	if pkg.Data, err = OutputPath("data"); err != nil {
		return err
	}

	return os.Symlink(dataDir, filepath.Join(pkg.Data, "testdata"))
}

func test(sdk *GoSDK) {
	attrs := derivation.GetAttrs[TestAttrs]()

	goSrcs, _, _, err := sortSrcs(attrs.Srcs)
	if err != nil {
		log.Fatalf("failed to enumerate internal source files: %v", err)
	}
	goXSrcs, _, _, err := sortSrcs(attrs.XSrcs)
	if err != nil {
		log.Fatalf("failed to enumerate external source files: %v", err)
	}

	pkg := &testPackage{ImportPath: attrs.ImportPath}
	name, err := pkg.findTestCases("_test", attrs.ImportPath, goSrcs)
	if err != nil {
		log.Fatal(err)
	}
	xname, err := pkg.findTestCases("_xtest", attrs.ImportPath+"_test", goXSrcs)
	if err != nil {
		log.Fatal(err)
	}
	if len(goSrcs) > 0 && len(goXSrcs) > 0 && xname != name+"_test" {
		log.Fatalf(
			"mismatched package names: expected %s, got %s",
			name+"_test",
			xname,
		)
	}

	if sdk.Compatible("1.18") {
		pkg.SupportsFuzz = true
	}
	if err := setupData(attrs.Data, pkg); err != nil {
		log.Fatal(err)
	}

	outDir, err := OutputPath("out")
	if err != nil {
		log.Fatal(err)
	}

	file, err := os.Create(filepath.Join(outDir, "testmain.go"))
	if err != nil {
		log.Fatal(err)
	}
	defer file.Close()

	tmpl := template.Must(template.New("test").Parse(testMainTmpl))
	if err := tmpl.Execute(file, &pkg); err != nil {
		log.Fatalf("error evaluating the template for test.go: %v", err)
	}
}
